input-file: "/home/daniil/mygithub/lets-go-programming-v2025-spring-spbstu/daniil.avdeev/task-3/test/input/5.xml"
output-file: "/home/daniil/mygithub/lets-go-programming-v2025-spring-spbstu/daniil.avdeev/task-3/test/output/5.json"
